### ISSUE TITLE
Node Editor

### ISSUE THREAD

**Issue by nexssp** [nexssp/cli#16]
Node Editor for Nexss Programmer packages and programs.

**Comment by mapoart** [comment]
Nexss Programmer will have it's own **Node Editor** but also Users will be albe to use _Nexss Programmer_ in many programs for example:
- **Blender** - There will be new node with _Nexss Programmer_ functionality (Open Source)
- **Natron** - Also Natron will have new nodes for _Nexss Programmer_ functionality (Open Source)

There will be more, however that ones are the next ones..

**Comment by mapoart** [comment]
This has been postponed.
