### ISSUE TITLE
Add !empty.[ext] to all languages

### ISSUE THREAD

**Issue by mapoart** [nexssp/cli#35]
Add empty.ext to all templates. It is an empty file so when creates new file with `nexss file add my.py`. It contains empty space at the beginning so it appears at the top of the list for the templates.

Done:
- **AutoHotKey**
- **AutoIt** 
- **Python**
- **PHP**
- **JS/NODEJS**
-

**Comment by mapoart** [comment]
PHP added.

**Comment by mapoart** [comment]
" empty.[ext]" seem not working. Different file is copied?

To review..

**Comment by nexssp** [comment]
I am closing this and create new one as all langs will have new empty template like `!empty[ext]` as it will appear at the begining of the list.
