### ISSUE TITLE
Add function to list all languages (not only installed ones)

### ISSUE THREAD

**Issue by mapoart** [nexssp/cli#40]
now `nexss l l` OR `nexss language list` displays installed languages (on demand).

- we need `nexss l i/nexss language installed`  (for installed)
- and `nexss l l` / `nexss language list` (for all available languages)

**Comment by nexssp** [comment]
![image](https://user-images.githubusercontent.com/53263666/120490200-7fc5cb80-c3b8-11eb-8898-654ec0252258.png)

Done with Nexss 2.5.x .
so 
`nexss l list` - list of all available languages
`nexss l installed` - list of all installed ones
