### ISSUE TITLE
Raku - raku command has not been found / Ubuntu 18 / Google Colab

### ISSUE THREAD

**Issue by mapoart** [nexssp/cli#45]
Raku does not work properly (maybe change to Perl6??)

**Comment by mapoart** [comment]
Windows works ok:
![image](https://user-images.githubusercontent.com/8799218/116215340-e1ef3900-a747-11eb-9eea-3d3f61b98f46.png)

**Comment by nexssp** [comment]
Fixed. Now Nexss Programmer installing 2021.04-01 version. It creates symbolic links (For future use of multiple versioning) as:
-  `/usr/bin/raku` and `/usr/bin/raku2021.04-01`
-  `/usr/bin/perl6` and `/usr/bin/perl62021.04-01`
-  `/usr/bin/rakudo` and `/usr/bin/rakudo2021.04-01`
-  `/usr/bin/zef` and `/usr/bin/zef` (package manager)

Below full installation script generated for Ubuntu distro by Nexss Programmer (On Google Colab Notebook):

![image](https://user-images.githubusercontent.com/53263666/116760407-23683880-aa15-11eb-9aba-c301a2b64b25.png)
