### ISSUE TITLE
Powershell - npm link issue on pipe

### ISSUE THREAD

**Issue by nexssp** [nexssp/cli#6]
This is not a show stopper, but rather enhancement

There is an issue on powershell npm-link script which runs nexss command:

when we installing nexss we use `npm-link` which makes some scripts to run (it depends where you have nodejs installed /bin folder):
![image](https://user-images.githubusercontent.com/53263666/72747190-39514180-3bb4-11ea-90fd-c3fce833ec61.png)

this nexss.ps1 command don't pass STDIN to the nexss properly for example:
```sh
echo '{"x":"y"}' | node nexss.js Id # works - so run from node without npm-link script
echo '{"x":"y"}' | nexss Id # doesn't work
```

**Comment by mapoart** [comment]
https://github.com/nexssp/language_powershell/wiki/Stdin-pass-to-exe-in-Powershell-(Issue-with-npm-link)

**Comment by nexssp** [comment]
done.
