### ISSUE TITLE
Add default.v and helloWorld.v for vlang

### ISSUE THREAD

**Issue by mapoart** [nexssp/cli#66]
Add templates for Vlang

**Comment by nexssp** [comment]
## Done:
![image](https://user-images.githubusercontent.com/53263666/116904394-eb900980-ac3d-11eb-8f04-3d7e5d74396a.png)

## Also added some error solutions eg. for util:

![image](https://user-images.githubusercontent.com/53263666/116904450-fc407f80-ac3d-11eb-817d-e407715ac971.png)

See more here: 

https://github.com/nexssp/language_v/blob/master/nexss.v.errors.js
