### ISSUE TITLE
Refactoring -> 2.3.0 -> 2.4.0

### ISSUE THREAD

**Issue by mapoart** [nexssp/cli#69]
-  Better coding structure
- much more efficient
- DRY

**Comment by mapoart** [comment]
---> 2.4.0

**Comment by nexssp** [comment]
A lot of refactoring done so far:
new modules:
@nexssp/min
@nexssp/test
@nexssp/const
@nexssp/dddebug
@nexssp/stack

upgraded modules:
@nexssp/os
